version: 2.0
jobs:
  build:
    docker:
      - image: gerey/circleci-cuda-image:latest
    working_directory: ~/work
    steps:
      - checkout
      - run: make -j 8
      - run: |
          ulimit -c unlimited
          ./OpenMP_HelloWorld
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps