version: 2.0
jobs:
  build:
    docker:
      - image: nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
    working_directory: ~/work
    steps:
      - checkout
      - run: make -j 8
      - run: |
          ulimit -c unlimited
          ./SimpleCudaC
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps